Add RealmLogoView.
realm-demos/realm-loginkit pull request #19
Opened 2017-02-21 12:53 UTC by dalinaum

- [x] Logo View
- [ ] Register part Viewgroup
- [ ] Sign in part Viewgroup
- [ ] Fragment or View which includes viewgroups.

2017-04-04 12:50 UTC, dalinaum commented
Please review this.

It doesn't include some icons such Server, Email, Password. Since they don't match Android's TextInputLayout.

![screenshot-2017-04-04_21 47 07 588](https://cloud.githubusercontent.com/assets/145585/24657268/88bb3162-1980-11e7-8acb-76d87c36a5c1.png)
![screenshot-2017-04-04_21 47 21 300](https://cloud.githubusercontent.com/assets/145585/24657269/88bb639e-1980-11e7-96fb-8d4d0d14a676.png)
![screenshot-2017-04-04_21 47 32 306](https://cloud.githubusercontent.com/assets/145585/24657270/88be345c-1980-11e7-97c6-31ac41058c00.png)
![screenshot-2017-04-04_21 47 47 978](https://cloud.githubusercontent.com/assets/145585/24657271/88bf2240-1980-11e7-9d45-d65d1d4506de.png)
![screenshot-2017-04-04_21 48 08 738](https://cloud.githubusercontent.com/assets/145585/24657272/88c5dbee-1980-11e7-8572-6f36b87e43a8.png)

2017-04-04 13:34 UTC, bmeike approved these changes
I'm have a couple questions, but nothing that blocks.

2017-04-04 13:34 UTC, bmeike commented on RealmLoginKit Android/.idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Do you really want to check in the .idea directory?

2017-04-04 13:34 UTC, bmeike commented on RealmLoginKit Android/app/build.gradle
> +    compile fileTree(dir: 'libs', include: ['*.jar'])
Are there actually any jars?  Would it make sense to remove this dependency?

2017-04-04 13:34 UTC, bmeike commented on RealmLoginKit Android/app/src/main/java/io/realm/realmloginkit/example/ExampleActivity.java
> +        final int minWidth;
perhaps:
final int minWidth = (int) (((width < height) ? width : height) * LOGO_RATION)

2017-04-04 13:34 UTC, bmeike commented on RealmLoginKit Android/app/src/main/java/io/realm/realmloginkit/example/ExampleActivity.java
> +        if (viewId == R.id.light_button) {
Perhaps this should be a switch?  If R.id.light_button is a constant (this is not a library) that will work.

2017-04-04 13:34 UTC, bmeike commented on RealmLoginKit Android/app/src/main/res/values/dimens.xml
> +<resources>
I don't see how to comment on those .png files.  Shouldn't we use our logo or something, for the launcher icon?

2017-04-04 14:06 UTC, zaki50 requested changes

2017-04-04 14:06 UTC, zaki50 commented on RealmLoginKit Android/.idea/copyright/profiles_settings.xml
> +<component name="CopyrightManager">
Do we need to include some files in `.idea/` directory?
If there is no particular reason, we should use the same `.gitignore` with other demo apps or `raelm-java`

2017-04-04 14:09 UTC, zaki50 commented on RealmLoginKit Android/app/src/main/java/io/realm/realmloginkit/example/ExampleActivity.java
> +        final int minWidth;
Or `Math.min(int,int)`

2017-04-04 14:13 UTC, dalinaum commented on RealmLoginKit Android/app/src/main/java/io/realm/realmloginkit/example/ExampleActivity.java
> +        final int minWidth;
OK. I will use mixed solution.

2017-04-04 14:22 UTC, dalinaum commented on RealmLoginKit Android/app/src/main/res/values/dimens.xml
> +<resources>
I agree with you. I will make a launcher icon.

2017-04-04 14:57 UTC, dalinaum commented on RealmLoginKit Android/app/src/main/res/values/dimens.xml
> +<resources>
@bmeike I updated a launcher icon.

2017-04-04 15:18 UTC, dalinaum commented on RealmLoginKit Android/.idea/copyright/profiles_settings.xml
> +<component name="CopyrightManager">
@zaki50 Removed the entire `.idea` and updated `.gitignore`.

2017-04-07 04:00 UTC, beeender commented
How easy to integrate this into user's app project? Need something about installation to the `README`?

2017-04-07 22:48 UTC, TimOliver approved these changes

2017-04-08 02:45 UTC, dalinaum commented
@beeender Of course, README should be updated. Although it is not delivered by J Center or other repositories, I don't know how can users install this library easily.

2017-04-10 23:56 UTC, TimOliver commented
I just downloaded and deployed it to one of the office Pixel tablets. It looks and behaves really nicely!

I think I found one small glitch. If you're holding the tablet in sideways, the keyboard overlays the password field, and there doesn't seem to be a way to scroll to it.

That's a very minor edge case, so I'm happy to merge this now and address it later.

Does anyone else think there are any outstanding issues that absolutely must be solved before we can go ahead and merge? :)

Thanks!

2017-04-11 06:27 UTC, dalinaum commented
Althought README.md should be updated and its layout should be scrolled, I think they are not big issues and they can be another PRs.

2017-04-11 08:43 UTC, beeender approved these changes
👍

2017-04-11 09:30 UTC, merged